# Generated by Django 5.0.6 on 2024-05-10 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='pic',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
