# Generated by Django 5.0.6 on 2024-05-10 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_comment_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='pic',
        ),
        migrations.AddField(
            model_name='post',
            name='pic',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
